### ISSUE TITLE
Support multiple file uploads in a single field

### ISSUE THREAD

**Issue by benkeen** [formtools/module-field_type_file#1]
This'll need the module to be revised, I think. But a very reasonable request!

**Comment by sf23103** [comment]
How will the file names be stored in the database when multiple files are uploaded from a single field? Just curious how this will be handled!

**Comment by benkeen** [comment]
Good question, I was pondering the same thing. So right now the field just stores the filename; the file folder + URL are associated with the field itself. So I was thinking of using the colon character as a delimiter to store all file upload names in the database field. A colon is an invalid character for filenames on both Mac + Windows boxes so it seems a sensible delimiter.

**Comment by sf23103** [comment]
Cool, that sounds reasonable.  I've got a couple of apps that display images on a page from particular submissions, so I was just thinking about how I'll handle that.  I'll just have to parse multiple images out from colon delimiters.  Should be easy enough, and the trouble well worth the ability to have multiple uploads in one a single field.

**Comment by benkeen** [comment]
This is now working. Should get it out today or tomorrow.
