### ISSUE TITLE
[BUG] More then one file field in a form with validation/Delete attachment doesn't work

### ISSUE THREAD

**Issue by stfour** [formtools/module-field_type_file#14]
When you fill a form (Form Builder) that contains at least two file field, if for some reason one of them is ok and uploaded successfully and the other not, and validation is enabled for both, it is impossible to "Continue" after uploading the correct file.
Also pressing "Delete File" and then "Yes" on confirm popup, do nothing.
Thank you
![err1](https://user-images.githubusercontent.com/10631426/52595355-00f69e80-2e4e-11e9-9a59-5bc52161c2dc.png)
![err2](https://user-images.githubusercontent.com/10631426/52595363-0522bc00-2e4e-11e9-95d4-b8bc738b5978.png)
![err3](https://user-images.githubusercontent.com/10631426/52595367-06ec7f80-2e4e-11e9-9d31-ffddcbabbf22.png)

**Comment by benkeen** [comment]
Confirmed, thanks @stfour I'll take a look at this.

**Comment by stfour** [comment]
Thank you ;)

**Comment by benkeen** [comment]
No problem! This one's fixed, but I'll look at that other issue you spotted tomorrow night (Export Manager module) - pretty sure it's also caused by this module. I won't release a new version until I've checked that out.

**Comment by stfour** [comment]
nice! ;)

**Comment by stfour** [comment]
I confirm this bug was solved. Thank you!
Marco
