### ISSUE TITLE
[BUG] Excel and CSV problems (3.0.5)

### ISSUE THREAD

**Issue by stfour** [formtools/module-field_type_file#16]
Hallo, it seems that excel export generate an html output in a xls file. CSV export break when there is a "file" form item. In this case it is an html ul/href column. I think it should be simple a link.
Thanks in advance.
Marco

**Comment by benkeen** [comment]
Thanks! I'll release an update to this module tonight. 

[Edit: I was mistaken, the Export Manager doesn't need to be updated - I was working off an old copy. ]

**Comment by stfour** [comment]
<del>Benkeen, I've updated to latest module-field_type_file, as I've reported the problem with attachment was solved, but still corruption with file field is present on csv and xls export.
Just to make you know it.</del>
Ciao
Marco

**Comment by stfour** [comment]
I'm sorry, delete my previous comment, it is working perfectly... I have not press "upgrade" after replacing the module files.

Good work ;)

**Comment by benkeen** [comment]
Good to hear, thanks!
